SEPARATOR = '——————————————————————————————————————————————————————'
SEPARATOR_START = '|    '
SEPARATOR_END = ' |'

DAYS_BEFORE_EXAM_FOR_EARLY_STUDY_END = 60

ITA_EXAM_DAY = 8
ITA_EXAM_MONTH = 10
ITA_EXAM_YEAR = 2024

AULAS_LICOES_DE_MATEMATICA = 1518
PAGINAS_TOPICOS_DE_FISICA = 1376
PAGINAS_MARTHA_REIS = 867

AULAS_FEITAS_LICOES_DE_MATEMATICA = 269
PAGINAS_FEITAS_TOPICOS_DE_FISICA = 152
PAGINAS_FEITAS_MARTHA_REIS = 139


